// <auto-generated />
namespace Passion_231.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class passion2310310305 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(passion2310310305));
        
        string IMigrationMetadata.Id
        {
            get { return "202103102005226_passion2310310305"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
